/// Clinical working draft combining the supplied specification with the
/// Base44 EKG module's organization. Not covered by Special Considerations signoff.
class EkgEntry {
  const EkgEntry(this.title, this.category, this.sections, this.sources);
  final String title;
  final String category;
  final Map<String, String> sections;
  final List<String> sources;
}

const bradySource = 'https://www.acc.org/-/media/Non-Clinical/Files-PDFs-Excel-MS-Word-etc/Guidelines/2018/Guidelines_Made_Simple_2018_Bradycardia.pdf';
const periopSource = 'https://professional.heart.org/-/media/PHD-Files-2/Science-News/2/2024/2024-Guideline-for-Perioperative-Cardiovascular-Management-slide-set.pdf?sc_lang=en';
const alsSource = 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/executive-summary';
const afSource = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11104284/';
const qtSource = 'https://resources.wfsahq.org/wp-content/uploads/atow-449-00.pdf';
const deviceSource = 'https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2024/07/17/14/48/periprocedural-management-and';
const stSource = 'https://litfl.com/st-segment-ecg-library/';
const ecgSource = 'https://litfl.com/ecg-library/diagnosis/';
const standardMonitoring = 'Continuous ECG, blood pressure, oxygenation and ventilation monitoring appropriate to the anesthetic. Obtain a diagnostic 12-lead ECG for a new or concerning change; a monitor strip does not replace it.';
const stableDecision = 'A stable, previously evaluated finding is not an automatic reason to cancel. New symptoms, hemodynamic compromise or an unexplained new abnormality require evaluation before elective anesthesia. Urgent surgery requires an individualized risk and treatment plan.';

EkgEntry rhythm(String title, String findings, String anesthesia,
    String decision, String monitoring, List<String> sources) =>
  EkgEntry(title, 'Rhythm Library', {
    'Key ECG Findings': findings,
    'Anesthesia Considerations': anesthesia,
    'Proceed vs Delay Considerations': decision,
    'Monitoring Requirements': monitoring,
  }, sources);

final ekgEntries = <EkgEntry>[
  rhythm('Atrial Fibrillation',
    'Irregularly irregular ventricular rhythm without consistent discrete P waves. QRS is often narrow, but aberrancy or pre-excitation can widen it.',
    'Assess ventricular rate, perfusion, triggers, ventricular function and the anticoagulation plan. Treat contributors such as pain, anemia and infection. Pre-excited AF is a distinct high-risk pathway; do not treat it as routine narrow-complex AF.',
    'Evaluate new or uncontrolled AF before elective anesthesia. Hemodynamic instability caused by AF requires urgent cardioversion, not routine elective progression.',
    '$standardMonitoring Review rate trends and reassess postoperative stroke risk and follow-up.',
    [afSource, periopSource, alsSource]),
  rhythm('Atrial Flutter',
    'Organized flutter activity, often sawtooth in inferior leads. Fixed AV conduction may give a regular ventricular rhythm; variable conduction may be irregular.',
    'Assess rate, perfusion, precipitating factors and thromboembolic risk. Do not assume a regular rhythm excludes an atrial arrhythmia.',
    'Evaluate new or poorly controlled flutter before elective anesthesia. Instability attributable to the rhythm calls for urgent electrical cardioversion.',
    standardMonitoring, [afSource, alsSource, periopSource]),
  rhythm('SVT',
    'Often a regular narrow-complex tachycardia with P waves hidden in or near the QRS. SVT is a category, not a single mechanism; flutter and sinus tachycardia remain important alternatives.',
    'Assess the patient before treating the tracing. Correct triggers and determine stability and QRS regularity/width. Do not apply a regular narrow-complex pathway to an irregular wide-complex rhythm.',
    'Resolve active sustained unexplained tachycardia before elective anesthesia. Instability requires immediate rhythm-directed resuscitation.',
    '$standardMonitoring Have cardioversion capability immediately available for significant active tachyarrhythmia.',
    [alsSource, periopSource, ecgSource]),
  rhythm('Junctional Rhythm',
    'Absent, inverted or retrograde P waves, sometimes before, within or after the QRS. QRS is usually narrow unless there is associated conduction disease.',
    'Assess perfusion and the significance of lost AV synchrony. Consider medications, vagal stimulation, ischemia and sinus-node dysfunction.',
    stableDecision, standardMonitoring, [bradySource, periopSource, ecgSource]),
  rhythm('Sinus Bradycardia',
    'Sinus P waves precede conducted QRS complexes at a slow rate. The clinical significance depends on symptoms and perfusion, not a rate label alone.',
    'Review baseline rate, AV-nodal-slowing drugs, vagal stimuli, oxygenation and reversible causes. Significant symptomatic bradycardia requires the current resuscitation pathway.',
    'Asymptomatic baseline bradycardia does not by itself mandate cancellation or pacing. New symptomatic bradycardia requires evaluation and stabilization.',
    '$standardMonitoring Ensure rapid access to pacing when clinically indicated.',
    [bradySource, periopSource]),
  rhythm('Sinus Tachycardia',
    'Sinus P waves with an accelerated rate, usually with a consistent P-QRS relationship.',
    'Look for pain, hypovolemia, anemia, fever, hypoxemia, infection and other physiologic stressors before attempting rate suppression.',
    'Persistent unexplained tachycardia should be evaluated before elective anesthesia. Treat instability and its cause rather than the monitor number alone.',
    standardMonitoring, [periopSource, ecgSource]),
  rhythm('PACs',
    'Premature atrial depolarizations with an early P wave of different morphology. Conduction may be normal, aberrant or blocked.',
    'Review symptoms, frequency, electrolyte disturbances and triggers. Distinguish blocked PACs from AV block before labeling conduction disease.',
    stableDecision, standardMonitoring, [ecgSource, periopSource]),
  rhythm('PVCs',
    'Premature ventricular complexes, usually wide and not preceded by a normally conducted P wave. Evaluate frequency, morphology, couplets and runs.',
    'Assess oxygenation, electrolytes, ischemic symptoms, ventricular function and change from baseline. Frequent or complex ectopy deserves more attention than isolated stable ectopy.',
    'Isolated asymptomatic ectopy is not an automatic cancellation. New frequent/complex ectopy, syncope, sustained VT or suspected ischemia warrants evaluation before elective anesthesia.',
    '$standardMonitoring Consider ambulatory assessment for burden when appropriate; a brief monitor strip does not quantify daily burden.',
    [ecgSource, periopSource]),
  rhythm('RBBB',
    'Complete RBBB has QRS duration at least 120 ms, terminal rightward forces in V1/V2 and a broad terminal S wave in lateral leads.',
    'Compare with prior ECGs and assess associated cardiopulmonary disease. Additional conduction abnormalities or syncope change the risk assessment.',
    stableDecision, standardMonitoring, [bradySource, periopSource]),
  rhythm('LBBB',
    'Complete LBBB has QRS duration at least 120 ms, broad/notched lateral R waves and secondary ST-T changes. Ischemia interpretation requires special care.',
    'Determine whether it is new and assess structural heart disease and ischemic symptoms. New LBBB alone is not proof of acute coronary occlusion.',
    'Evaluate unexplained new LBBB before elective anesthesia. Symptoms or instability suggesting ACS require urgent evaluation regardless of whether formal STEMI criteria are met.',
    '$standardMonitoring Compare baseline ECGs; consider echocardiography and expert interpretation based on clinical context.',
    [bradySource, periopSource, stSource]),
  rhythm('1st Degree AV Block',
    'PR interval greater than 200 ms with 1:1 AV conduction; no P wave is dropped.',
    'Review AV-nodal-slowing medications and coexisting conduction disease. Marked PR prolongation may affect AV synchrony.',
    stableDecision, standardMonitoring, [bradySource, periopSource]),
  rhythm('Mobitz I',
    'Typically progressive PR prolongation before a nonconducted P wave, then repetition. A 2:1 pattern cannot reliably be classified as Mobitz I or II from that pattern alone.',
    'Assess symptoms, vagal tone, medications and QRS width. Do not assume all second-degree block is benign or nodal.',
    'Previously assessed asymptomatic nodal block may be compatible with proceeding. New, symptomatic or uncertain-site block warrants evaluation.',
    '$standardMonitoring Escalate monitoring and pacing preparedness when symptoms or suspected infranodal disease are present.',
    [bradySource, periopSource]),
  rhythm('Mobitz II',
    'Intermittent nonconducted P waves with constant PR intervals in conducted beats. Exclude blocked ectopy and do not classify isolated 2:1 conduction as Mobitz II without further assessment.',
    'Risk of progression to complete block. Identify reversible causes and obtain a pacing plan; do not rely on atropine to resolve infranodal disease.',
    'New or untreated Mobitz II requires cardiology/pacing evaluation before elective anesthesia. Acquired nonreversible Mobitz II is an indication for permanent pacing regardless of symptoms.',
    'Continuous ECG and perfusion monitoring with immediate pacing/resuscitation capability; decide on invasive pressure monitoring individually.',
    [bradySource, periopSource]),
  rhythm('3rd Degree AV Block',
    'No AV conduction; atrial and ventricular activity are independent. The escape rate and QRS width depend on the escape focus.',
    'Cardiac output depends on the escape rhythm or established pacing. Review reversible causes and ensure a reliable pacing strategy.',
    'Stabilize and establish an appropriate pacing plan before elective anesthesia. Urgent surgery requires coordinated anesthesia and cardiology management.',
    'Continuous ECG plus mechanical pulse/perfusion monitoring; pacing and resuscitation capability immediately available.',
    [bradySource, periopSource]),
  rhythm('Ventricular Tachycardia',
    'Wide-complex tachycardia may represent VT; AV dissociation, capture and fusion beats support the diagnosis. Absence of these findings does not exclude it.',
    'Immediately determine pulse, perfusion and whether the rhythm is monomorphic or polymorphic. Do not assume an uncertain wide-complex tachycardia is benign SVT.',
    'Active sustained VT is not an elective proceed condition. Pulseless VT follows the shockable arrest pathway; unstable monomorphic VT with a pulse requires urgent synchronized cardioversion.',
    'Continuous ECG and perfusion assessment with a defibrillator immediately available. Use the current resuscitation protocol, including device-specific energy settings.',
    [alsSource, periopSource, ecgSource]),
  rhythm('Ventricular Fibrillation',
    'Chaotic ventricular electrical activity without organized effective contraction. Assess the patient and exclude artifact without delaying arrest care.',
    'Activate the emergency response, begin high-quality CPR and defibrillate promptly according to the current adult arrest algorithm.',
    'Cardiac arrest: resuscitation takes priority over elective surgery.',
    'Resuscitation monitoring, defibrillation and waveform capnography when an advanced airway is present. Identify reversible causes.',
    [alsSource, ecgSource]),
  rhythm('Torsades de Pointes',
    'Polymorphic VT with changing QRS axis/amplitude in the setting of prolonged repolarization. Not every polymorphic VT is torsades.',
    'Sustained polymorphic VT requires immediate unsynchronized shock. Address QT-prolonging drugs and electrolyte causes; magnesium and other recurrence-prevention measures must not delay defibrillation.',
    'Active torsades or uncorrected high-risk acquired QT prolongation is not an elective proceed condition.',
    'Continuous ECG with immediate defibrillation capability. Reassess QT, potassium, magnesium and calcium; ongoing monitoring is needed after an episode.',
    [alsSource, qtSource]),
  rhythm('WPW',
    'Manifest pre-excitation may show short PR, a delta wave and widened QRS. Pre-excited AF is typically an irregular wide-complex tachycardia.',
    'Avoid adrenergic triggers and establish a rhythm-specific plan. In pre-excited AF, AV-nodal blockers including adenosine, beta blockers, verapamil/diltiazem, digoxin and amiodarone are contraindicated. This restriction is not interchangeable with the regular orthodromic AVRT pathway.',
    'Symptomatic or high-risk pre-excitation requires specialist evaluation before elective anesthesia. Hemodynamically unstable pre-excited AF requires electrical cardioversion.',
    'Continuous ECG and perfusion monitoring with immediate cardioversion/defibrillation capability. Monitoring intensity depends on symptoms and procedural risk.',
    [afSource, 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6211613/']),
  rhythm('Brugada Pattern',
    'Type 1 morphology includes coved right-precordial ST elevation with T-wave inversion. A pattern requires expert interpretation; it is not interchangeable with a complete clinical syndrome diagnosis.',
    'Avoid fever, electrolyte disturbance and known provoking drugs. Review syncope, ventricular arrhythmia history and any ICD plan.',
    'A newly recognized pattern, syncope, fever-triggered changes or prior malignant arrhythmia calls for specialist planning before elective anesthesia.',
    'Continuous ECG, temperature and perfusion monitoring with defibrillation available. Postoperative monitoring is individualized to risk and events.',
    ['https://pmc.ncbi.nlm.nih.gov/articles/PMC4881698/', periopSource, deviceSource]),
  rhythm('Long QT Syndrome',
    'Prolonged corrected QT may be congenital or acquired. Confirm measurement, correction method, heart rate and QRS width; one automated QTc does not establish the diagnosis.',
    'Review QT-prolonging drugs and interactions; correct potassium, magnesium and calcium disturbances. Continue indicated chronic beta blockade for congenital LQTS and minimize abrupt sympathetic stimulation.',
    'Significant QT prolongation, prior life-threatening arrhythmia or correctable acquired causes require optimization and a specialist plan before elective anesthesia.',
    'Baseline 12-lead ECG, continuous ECG and temperature monitoring; defibrillator and magnesium available. Continue appropriate recovery monitoring.',
    [qtSource, periopSource]),
  EkgEntry('Normal Sinus Rhythm', 'Base44 Reference Extras', {
    'Key ECG Findings': 'Consistent sinus P waves with a P before each conducted QRS and a regular overall rhythm. Assess intervals, axis and ST-T changes separately.',
    'Perioperative Context': 'A sinus rhythm label does not exclude ischemia, structural disease or electrolyte abnormalities.',
  }, [ecgSource]),
  EkgEntry('Asystole and PEA', 'Base44 Reference Extras', {
    'Recognition': 'Asystole is absent ventricular electrical activity; verify the tracing and connections promptly. PEA is electrical activity without a palpable pulse, not a single ECG morphology.',
    'Emergency Priority': 'Both are nonshockable arrest pathways: immediate high-quality CPR, current resuscitation protocol and reversible-cause evaluation. Do not shock asystole or PEA. Routine pacing is not a treatment for established asystolic cardiac arrest.',
  }, [alsSource]),
  ...[
    ['Inferior', 'II, III, aVF', 'RCA or LCx', 'Assess for right-ventricular involvement and bradycardia/AV block. Obtain right-sided leads when indicated.'],
    ['Anterior', 'V1–V4 (anteroseptal distribution)', 'LAD', 'Assess ventricular dysfunction, shock and ventricular arrhythmia risk.'],
    ['Lateral', 'I, aVL, V5–V6', 'LCx or LAD diagonal branches', 'Look for reciprocal changes and associated territory involvement.'],
    ['Septal', 'V1–V2', 'LAD septal branches', 'Confirm lead placement and interpret with adjacent leads; conduction abnormalities may coexist.'],
    ['Posterior', 'Reciprocal ST depression in V1–V3; posterior leads V7–V9', 'RCA or LCx', 'Consider posterior leads when the anterior pattern suggests posterior injury. Do not label all anterior ST depression as anterior ischemia.'],
    ['Right Ventricular', 'Right-sided leads, especially V4R; often with inferior involvement', 'Usually proximal RCA', 'Assess RV function and perfusion; avoid indiscriminate preload reduction or fluid loading. Tailor hemodynamic management.'],
    ['Anterolateral', 'Anterior plus lateral lead distributions', 'LAD and/or LCx territory, anatomy dependent', 'Potentially extensive injury; assess shock and arrhythmia risk promptly.'],
    ['aVR with Diffuse ST Depression', 'ST elevation in aVR with widespread ST depression', 'Not a specific artery diagnosis', 'May reflect severe coronary disease or supply-demand mismatch. It does not by itself prove acute left-main occlusion. Assess the patient and seek urgent expert evaluation when ACS is suspected.'],
  ].map((r) => EkgEntry(r[0], 'Ischemia & Territories', {
    'Lead Distribution': r[1],
    'Likely Coronary Territory': r[2],
    'Anesthesia Implications': r[3],
    'Safety Context': 'Lead-to-artery correlation is approximate. New ischemic changes require clinical assessment, diagnostic ECG and an ACS pathway as indicated; this table is not a stand-alone STEMI diagnostic rule or elective surgical clearance.',
  }, [stSource, 'https://litfl.com/st-depression-does-not-localise/', periopSource])),
  ...[
    ['Hyperkalemia', 'Peaked T waves, PR prolongation, diminished P waves or QRS widening may occur. A normal ECG does not exclude dangerous hyperkalemia.', 'Confirm laboratory results promptly without delaying treatment of instability. Assess renal function, potassium-raising drugs and acid-base status; severe abnormalities require correction before elective anesthesia.'],
    ['Hypokalemia', 'T-wave flattening/inversion, ST depression and prominent U waves may occur; apparent QT prolongation may be a prolonged QU interval.', 'Assess arrhythmia risk and coexisting magnesium deficiency. Correction decisions depend on severity, symptoms and the clinical setting, not an isolated ECG pattern.'],
    ['Hypercalcemia', 'Shortening of the ST segment and QT interval may occur.', 'Assess hydration, renal function and the cause; severe symptomatic disease requires stabilization. Do not use the QT interval to estimate a calcium concentration.'],
    ['Hypocalcemia', 'QT prolongation, principally through ST-segment prolongation, may occur.', 'Check ionized calcium when indicated, including major transfusion contexts. Assess neuromuscular symptoms and rhythm risk.'],
    ['Hypermagnesemia', 'Bradycardia, PR/QRS prolongation and AV block may occur with significant toxicity.', 'Assess renal clearance and magnesium exposure. Magnesium can enhance neuromuscular blockade and respiratory depression; monitor ventilation, circulation and neuromuscular recovery.'],
    ['Hypomagnesemia', 'Repolarization abnormalities and ventricular arrhythmias, including torsades risk, may occur; ECG findings are not specific.', 'Assess potassium and calcium concurrently. Identify losses and medication causes; correct clinically important deficits and monitor rhythm.'],
  ].map((r) => EkgEntry(r[0], 'Electrolytes', {
    'ECG Manifestations': r[1],
    'Perioperative Implications': r[2],
    'Interpretation Caution': 'Use measured electrolytes and clinical context. ECG appearance cannot reliably determine a serum concentration or exclude a serious disturbance.',
  }, [ecgSource, qtSource, 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10384947/'])),
  EkgEntry('PR, QRS and QTc', 'Intervals & Perioperative Pearls', {
    'PR': 'First-degree AV delay has PR greater than 200 ms with 1:1 conduction. A short PR is not by itself proof of WPW; look for pre-excitation morphology.',
    'QRS': 'A QRS of at least 120 ms is wide in adults. Determine morphology and compare the baseline; width alone does not identify the mechanism.',
    'QTc': 'Measure QT from QRS onset to the end of T, excluding a distinct U wave. Bazett: QT / square root of RR, using seconds. Bazett overcorrects at high rates and undercorrects at low rates. Wide QRS complicates QT interpretation.',
    'Clinical Context': 'Confirm concerning automated values manually; risk assessment includes symptoms, drugs, electrolytes and previous arrhythmias.',
  }, [bradySource, qtSource]),
  EkgEntry('Monitor Leads and Artifact', 'Intervals & Perioperative Pearls', {
    'Lead Selection': 'Select leads suited to rhythm and ischemia assessment; no single monitor lead excludes ischemia. Obtain a diagnostic 12-lead ECG for concerning changes.',
    'Artifact Check': 'Check the patient, mechanical pulse, electrodes and another lead. Do not let equipment troubleshooting delay resuscitation in a clinically unstable patient.',
    'ST Changes': 'Compare with baseline and consider rate, conduction changes, pacing, lead placement and clinical context. ST depression alone does not reliably localize an artery.',
  }, [periopSource, stSource, 'https://litfl.com/st-depression-does-not-localise/']),
  EkgEntry('High-Yield Anesthesia Findings', 'Intervals & Perioperative Pearls', {
    'Brugada / WPW / Long QT': 'Open the corresponding rhythm cards for trigger avoidance, medication cautions and monitoring. A pattern label does not replace a specialist plan.',
    'New LBBB / Ischemic Changes': 'Compare prior ECGs and evaluate new abnormalities. New LBBB alone does not establish an acute occlusion; concerning symptoms or instability require urgent evaluation.',
    'Ventricular Ectopy Burden': 'Assess symptoms, complexity, frequency and ventricular function. Daily burden requires appropriate monitoring rather than inference from one strip.',
  }, [periopSource, bradySource, qtSource, afSource]),
  EkgEntry('Preoperative Device Plan', 'Pacemaker & ICD', {
    'Identify': 'Device type, manufacturer/model, indication, battery status, recent interrogation, underlying rhythm and pacing dependence.',
    'Plan': 'Coordinate with the device team when EMI is anticipated. Confirm the actual magnet response; do not assume a universal response.',
    'Procedure Context': 'Consider generator location, cautery path, access to the device, patient position and whether a magnet can remain securely positioned.',
  }, [deviceSource, periopSource]),
  EkgEntry('Magnet Effects', 'Pacemaker & ICD', {
    'Pacemaker': 'Many transvenous pacemakers respond with asynchronous pacing, but the response is device- and programming-dependent. Verify it before relying on it.',
    'ICD': 'A magnet generally suspends tachyarrhythmia therapy while applied; it does not convert the pacing function to asynchronous mode. A pacing-dependent ICD patient may require reprogramming.',
    'Leadless Devices': 'Micra does not respond to a magnet. Some other leadless devices have magnet responses; use model-specific guidance and testing.',
    'MRI': 'A magnet is not a substitute for a formal MRI-conditional device protocol and specialist programming.',
  }, [deviceSource]),
  EkgEntry('EMI and Cautery', 'Pacemaker & ICD', {
    'Risk': 'EMI can inhibit pacing through oversensing or trigger inappropriate ICD therapy. Risk depends on proximity, current path and the procedure, not only device presence.',
    'Precautions': 'Coordinate cautery strategy and return-electrode placement to minimize current near the system; use brief bursts and bipolar equipment when feasible under the procedural plan.',
    'Pacing Dependence': 'For expected significant EMI, arrange an appropriate asynchronous pacing strategy when indicated. An ICD magnet alone does not prevent pacing inhibition.',
  }, [deviceSource, periopSource]),
  EkgEntry('Monitoring and Recovery', 'Pacemaker & ICD', {
    'During the Procedure': 'Monitor mechanical pulse/perfusion as well as ECG because artifact may obscure rhythm. External pacing and defibrillation capability must be available when device therapies are suspended.',
    'Before Leaving Monitored Care': 'Restore required programming and re-enable ICD tachyarrhythmia detection/therapy. Communicate changes and significant events to the device team.',
    'Follow-up': 'Arrange interrogation after significant events or when required by the device plan; document the final device status.',
  }, [deviceSource, periopSource]),
];
