-- Authorized adult perioperative antihypertensive quick charts.
begin;

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('antihypertensive-bolus','antihypertensive-dosing','Antihypertensive Dosing','IV bolus chart',array['antihypertensive','antihypertensives','hypertension','HTN','high blood pressure','BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','bolus','push','labetalol','Trandate','hydralazine','Apresoline','esmolol','Brevibloc','metoprolol','Lopressor','beta blocker','tachycardia','dose','dosing','onset','duration','delayed peak','off label','asthma','bradycardia','heart block','CAD'],0,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('antihypertensive-bolus','| Medication | Adult IV dose · timing · pertinent details |
|---|---|
| **Labetalol** | **Perioperative small bolus: 2.5–10 mg over 2 min**; individualized anesthesia dosing, not the labeled severe-hypertension escalation regimen. Onset 5–15 min. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC6148691/)) **Labeled severe hypertension:** 20 mg over 2 min, then 40–80 mg every 10 min as needed; **300 mg cumulative maximum**. Peak effect usually within 5 min of each labeled injection; effect persists for hours. Avoid asthma, severe bradycardia, greater-than-first-degree block, overt HF/cardiogenic shock. ([Prescribing information](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492)) |
| **Hydralazine** | **5 mg slow IV** is a low-dose perioperative option; this differs from the larger labeled 20–40 mg dose. Onset **5–20 min**; effect often **2–6 h**, potentially longer. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC6148691/); [Label](https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=f1a10203-f027-4f9c-8dd6-907c6db24d47&type=display)) Published perioperative repeat interval **20–60 min**; reassess before redosing because peak may take **10–80 min** and the effect is unpredictable. ([Perioperative dosing review](https://pmc.ncbi.nlm.nih.gov/articles/PMC2515421/)) Reflex tachycardia; contraindicated in CAD and rheumatic mitral valve disease. ([Label](https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=f1a10203-f027-4f9c-8dd6-907c6db24d47&type=display)) |
| **Esmolol** | **Gradual control: 500 mcg/kg (0.5 mg/kg) over 1 min**, then infusion if needed. **Immediate perioperative control: 1 mg/kg over 30 sec**, then 150 mcg/kg/min if needed; select regimen by clinical urgency and hemodynamics. ([Brevibloc label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) Onset **1–2 min**; effect roughly **10–30 min**. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC6148691/); [BP review](https://pmc.ncbi.nlm.nih.gov/articles/PMC4178624/)) Watch bradycardia, hypotension, AV block, decompensated HF and bronchospasm; do not suppress compensatory tachycardia from hypovolemia. ([Label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Metoprolol tartrate** | **2.5–5 mg IV over 1 min**; may repeat every **2–5 min** to **15 mg total**, titrating to BP/HR response. Peak response about **20 min**; duration **5–8 h**, so avoid rapid dose stacking. ([Hospital IV manual](https://pdtm.vch.ca/Documents/metoprolol%20NEW.pdf)) **IV use for hypertension is off-label in the US**; the US injection label is for stable acute MI, not a general BP protocol. Avoid significant bradycardia/block, hypotension and decompensated HF; caution with bronchospasm. ([US label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('antihypertensive-infusion','antihypertensive-dosing','Antihypertensive Dosing','IV infusion chart',array['antihypertensive','antihypertensives','hypertension','HTN','high blood pressure','BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','infusion','drip','nicardipine','Cardene','clevidipine','Cleviprex','esmolol','Brevibloc','labetalol','Trandate','nitroglycerin','NTG','nitroprusside','SNP','Nipride','Nitropress','Nipride RTU','titration','dose','dosing','maximum','egg allergy','soy allergy','aortic stenosis','cyanide','renal','lipid','PDE5','sildenafil','tadalafil','vardenafil','riociguat','nitrate','asthma','bradycardia','heart block'],1,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('antihypertensive-infusion','| Medication | Adult IV infusion · titration · pertinent details |
|---|---|
| **Nicardipine (Cardene)** | Start **5 mg/h**; increase by **2.5 mg/h every 5–15 min**; **maximum 15 mg/h**. Onset within minutes; about **50% offset in 30 min**, with residual effect potentially lasting hours. Watch reflex tachycardia, hypotension and phlebitis; **contraindicated in advanced aortic stenosis**. ([Prescribing information](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/022276Origs027lbl.pdf)) |
| **Clevidipine (Cleviprex)** | Start **1–2 mg/h**; initially may double every **90 sec**. Near goal, use smaller increases every **5–10 min**. Usual **4–6 mg/h**; most patients ≤16 mg/h; **32 mg/h only limited short-term experience**. Onset **2–4 min**; offset **5–15 min**. **Do not exceed 1,000 mL/24 h** (label average limit 21 mg/h); count other lipid sources. Contraindicated with **egg/soy allergy, defective lipid metabolism, or severe AS**. Discard vial **12 h after puncture**. ([Prescribing information](https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=f9290625-b723-4eda-bab8-a97bef6041f6&type=display)) |
| **Esmolol (Brevibloc)** | Gradual control: after **500 mcg/kg over 1 min**, start **50 mcg/kg/min for 4 min**; titrate stepwise to **100, 150, then 200 mcg/kg/min**, reassessing at 4-min steps. **Hypertension may require 250–300 mcg/kg/min**; >300 not studied. **Tachycardia maintenance >200 mcg/kg/min is not recommended.** Immediate perioperative regimen: **1 mg/kg over 30 sec**, then **150 mcg/kg/min** if needed. Monitor ECG/BP; avoid bradycardia/block, decompensated HF, shock, and closely timed IV verapamil. ([Prescribing information](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Labetalol** | Label example: **2 mg/min**, adjusted to BP response; usual effective total **50–200 mg**, up to **300 mg**. Effect persists for hours; not a rapid-offset infusion. Keep supine and assess orthostatic tolerance before ambulation. Avoid asthma, severe bradycardia/block and overt HF/cardiogenic shock. ([Prescribing information](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492)) |
| **Nitroglycerin (NTG)** | Start **5 mcg/min** with non-adsorptive tubing; increase by **5 mcg/min every 3–5 min** to 20 mcg/min, then increments of **10–20 mcg/min** if needed; smaller/slower changes after response. **No universal maximum in the label**: follow local limits. Infusion only; concentrated product must be diluted. ([Label](https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=b8af0974-33ea-4dd5-9ff7-3b61272aeb25&type=display)) Onset **2–5 min**, offset about **3–5 min**; mainly venodilates. ([BP review](https://pmc.ncbi.nlm.nih.gov/articles/PMC4178624/)) **Contraindicated with PDE5 inhibitors or riociguat**. ([FDA](https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2014/019970Orig1s015ltr.pdf)) Caution in preload-dependent states/RV infarction. ([NTG review](https://pmc.ncbi.nlm.nih.gov/articles/PMC9278720/)) |
| **Sodium nitroprusside (SNP)** | Start **0.3 mcg/kg/min**; assess BP for **at least 5 min** before retitration. **Maximum 10 mcg/kg/min**; keep exposure as short as possible. Onset **1–2 min**; hypotensive effect resolves in **1–10 min** after stopping. Continuous BP monitoring and infusion pump required. Cyanide risk increases above **2 mcg/kg/min**; hepatic dysfunction increases risk. For **eGFR <30**, mean rate **<3 mcg/kg/min**; for **anuria**, mean rate **≤1 mcg/kg/min**. Avoid PDE5 inhibitors/riociguat; consider ICP and thiocyanate accumulation. ([Prescribing information](https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/209387s004lbl.pdf)) As a conservative perioperative ceiling, **10 mcg/kg/min for <10 min**, not a maintenance rate. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC2515421/)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('antihypertensive-safety','antihypertensive-dosing','Antihypertensive Dosing','Monitoring & high-risk cautions',array['antihypertensive','antihypertensives','hypertension','HTN','high blood pressure','BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','monitoring','units','mg','mcg','micrograms','bolus stacking','delayed peak','pain','anesthetic depth','hypercarbia','hypoxia','bradycardia','beta blocker','blood pressure target'],2,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('antihypertensive-safety','| Check | Pertinent detail |
|---|---|
| **Scope** | Adult, monitored perioperative IV reference only; not pediatric, obstetric, stroke, aortic-dissection, or outpatient treatment protocols. Confirm concentration, order, local protocol and patient-specific BP/HR targets. |
| **Treat the cause** | Check pain/anesthetic depth, hypoxemia, hypercarbia, shivering, bladder distension and volume status before simply adding antihypertensives. ([Perioperative BP review](https://pmc.ncbi.nlm.nih.gov/articles/PMC4178624/)) |
| **Units** | Nicardipine/clevidipine: **mg/h**. Labetalol infusion: **mg/min**. Nitroglycerin: **mcg/min**. Esmolol/nitroprusside: **mcg/kg/min**. ([Perioperative dosing table](https://pmc.ncbi.nlm.nih.gov/articles/PMC4178624/)) Verify pump concentration; do not copy mL/h between products. |
| **Beta-blockers** | Monitor ECG, HR and BP; assess for bradycardia, conduction disease, decompensated HF and bronchospasm. Do not treat hypovolemia-related compensatory tachycardia with esmolol. ([Brevibloc label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Delayed peak / overshoot** | Hydralazine peak may take **10–80 min**; metoprolol peak about **20 min**. Reassess before repeating and account for all drugs already given. ([Hydralazine label](https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=f1a10203-f027-4f9c-8dd6-907c6db24d47&type=display); [Metoprolol IV manual](https://pdtm.vch.ca/Documents/metoprolol%20NEW.pdf)) |
| **Treatment target** | Avoid abrupt overshoot and preserve organ perfusion; the appropriate reduction depends on the clinical syndrome and baseline BP, not one universal target. ([Perioperative hypertension review](https://pmc.ncbi.nlm.nih.gov/articles/PMC2515421/)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

commit;
