-- Authorized adult beta-blocker quick charts.
begin;

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('beta-blocker-bolus','beta-blocker-dosing','Beta-Blocker Dosing','IV bolus chart',array['beta blocker','beta blockers','beta adrenergic','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','bolus','push','esmolol','Brevibloc','metoprolol','tartrate','Lopressor','labetalol','Trandate','Normodyne','propranolol','Inderal','AF','AFib','RVR','rate control','hypertension','tachycardia','medication','pertinent','details','brevibloc','gradual','control','mcg','over','min','then','infusion','needed','immediate','sec','choose','urgency','and','hemodynamic','tolerance','these','are','alternative','regimens','elimination','half-life','approximately','not','guaranteed','recovery','time','fda','label','lopressor','stable','rate','doses','maximum','reassess','before','each','guideline','this','off-label','the','injection','for','hemodynamically','acute','rapidly','reversible','use','oral','extended-release','succinate','small','individualized','anesthesia','practice','review','separate','severe-hypertension','regimen','every','cumulative','peak','effect','usually','within','avoid','asthma','severe','bradycardia','greater-than-first-degree','block','overt','cardiogenic','shock','inderal','repeat','nonselective','beta','blockade','contraindicated','sinus','cautiously','with','anesthesia-related','myocardial','depression','pre-excited','other','accessory-pathway','rhythms','require','rhythm-specific','assessment','blanket','wpw','rule','see','safety','chart','syndrome'],0,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('beta-blocker-bolus','| Medication | Adult IV dose · pertinent details |
|---|---|
| **Esmolol (Brevibloc)** | **Gradual control: 500 mcg/kg (0.5 mg/kg) over 1 min**, then infusion as needed. **Immediate perioperative control: 1 mg/kg over 30 sec**, then **150 mcg/kg/min** if needed. Choose by urgency and hemodynamic tolerance; these are alternative regimens. Elimination half-life approximately **9 min**, not a guaranteed recovery time. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Metoprolol tartrate (Lopressor)** | **Stable AF rate control: 2.5–5 mg over 2 min**, up to **3 doses (maximum 15 mg)**; reassess BP/HR before each dose. ([AF guideline](https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193)) This is **off-label in the US**; the US injection label is for hemodynamically stable acute MI. Half-life **3–7 h**: not rapidly reversible. Use **tartrate**, not oral extended-release succinate. ([US label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205)) |
| **Labetalol** | **Perioperative small bolus: 2.5–10 mg over 2 min**, individualized anesthesia practice. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC6148691/)) **Separate severe-hypertension label regimen:** **20 mg over 2 min**, then **40–80 mg every 10 min** as needed; **300 mg cumulative maximum**. Peak BP effect usually within **5 min** of each injection. Avoid asthma, severe bradycardia, greater-than-first-degree block, overt HF and cardiogenic shock. ([Label](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492)) |
| **Propranolol (Inderal)** | **AF guideline regimen: 1 mg over 1 min**, repeat every **2 min** as needed, up to **3 doses (3 mg)**. ([AF guideline](https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193)) Nonselective beta blockade; **contraindicated in asthma, sinus bradycardia, greater-than-first-degree block and cardiogenic shock**. Use cautiously with anesthesia-related myocardial depression. **Do not use for pre-excited AF**; other accessory-pathway rhythms require rhythm-specific assessment, not a blanket WPW rule. See safety chart and WPW Syndrome. ([Label](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f14ea537-dd5c-4c78-9037-9a85e9e610ef); [AF guideline](https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193)) |','2026-09-27-audit1')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('beta-blocker-infusion','beta-blocker-dosing','Beta-Blocker Dosing','IV infusion chart',array['beta blocker','beta blockers','beta adrenergic','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','infusion','drip','esmolol','Brevibloc','labetalol','Trandate','Normodyne','landiolol','Rapiblyk','SVT','AF','AFib','RVR','flutter','rate control','titration','maximum','impaired cardiac function','pulmonary hypertension','verapamil','medication','pertinent','details','brevibloc','gradual','control','svt','optional','mcg','over','min','then','for','needed','repeat','loading','doses','with','steps','each','increase','maintenance','not','recommended','hypertension','may','require','studied','avoid','close-proximity','contraindicated','pulmonary','decompensated','shock','severe','sinus','bradycardia','sick','syndrome','and','greater-than-first-degree','block','fda','label','adjusted','response','usual','effective','total','this','bp-control','regimen','standard','rate-control','keep','supine','assess','orthostatic','tolerance','before','ambulation','asthma','overt','cardiogenic','rapiblyk','including','normal','cardiac','function','start','every','impaired','either','continuous','bolus','the','limited','data','beyond','half-life','approximately','prescribing','information'],1,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('beta-blocker-infusion','| Medication | Adult IV infusion · titration · pertinent details |
|---|---|
| **Esmolol (Brevibloc)** | **Gradual control/SVT:** optional **500 mcg/kg over 1 min**, then **50 mcg/kg/min for 4 min**. If needed, optional repeat loading doses with steps to **100**, then **150 mcg/kg/min**, each for **4 min**; increase to **200 mcg/kg/min** if needed. **HR control: maintenance >200 mcg/kg/min not recommended.** Perioperative **hypertension** may require **250–300 mcg/kg/min**; >300 not studied. Avoid close-proximity **IV verapamil**; contraindicated in pulmonary hypertension, decompensated HF, shock, severe sinus bradycardia, sick sinus syndrome and greater-than-first-degree block. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Labetalol** | **Severe hypertension:** label infusion **2 mg/min**, adjusted to BP response; usual effective total **50–200 mg**, up to **300 mg**. This is a BP-control regimen, not a standard AF rate-control infusion. Keep supine; assess orthostatic tolerance before ambulation. Avoid asthma, severe bradycardia/block, overt HF and cardiogenic shock. ([Label](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492)) |
| **Landiolol (Rapiblyk)** | **Adult SVT, including AF/flutter:** normal cardiac function, start **9 mcg/kg/min**, increase **9 mcg/kg/min every 10 min**. Impaired cardiac function, start **1 mcg/kg/min**, increase **1 mcg/kg/min every 15 min**. **Maximum 36 mcg/kg/min** for either regimen. **Continuous infusion; no bolus in the US label.** Limited data beyond 24 h; half-life approximately **4 min**. Contraindicated in pulmonary hypertension, decompensated HF, shock, severe sinus bradycardia, sick sinus syndrome and greater-than-first-degree block. ([US prescribing information](https://www.rapiblyk.com/fileadmin/user_upload/MediaLibrary_Rapiblyk/Documents/Rapiblyk_Full_Prescribing_Information.pdf)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('beta-blocker-safety','beta-blocker-dosing','Beta-Blocker Dosing','Safety & perioperative use',array['beta blocker','beta blockers','beta adrenergic','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','safety','contraindications','interactions','esmolol','Brevibloc','metoprolol','Lopressor','labetalol','Trandate','Normodyne','propranolol','Inderal','landiolol','Rapiblyk','WPW','preexcited','pre excited AF','accessory pathway','AV nodal blockers','unstable AF','cardioversion','asthma','bronchospasm','verapamil','diltiazem','digoxin','bradycardia','heart block','pheochromocytoma','alpha blockade','hypoglycemia','glucose','fasting','chronic','continue','hold','morning of surgery','day of surgery','initiation','7 days','units','concentration','hypovolemia','compensatory tachycardia','check','pertinent','detail','scope','monitored','quick','reference','not','pediatric','obstetric','thyroid-storm','overdose','outpatient','oral-titration','protocols','confirm','indication','local','protocol','and','patient-specific','targets','before','ecg','rhythm','perfusion','volume','status','ventricular','function','suppress','compensatory','tachycardia','from','monitor','during','administration','reduce','stop','for','clinically','significant','hypotension','bradyarrhythmia','label','cardiac','risks','give','cardiogenic','shock','decompensated','severe','block','sinus-node','disease','requires','product-specific','assessment','pacemaker','does','remove','negative-inotropy','risk','acute-mi','also','contraindicates','min','sbp','mmhg','sec','these','are','label-specific','thresholds','universal','treatment','pre-excited','wpw','avoid','beta-blockers','other','av-nodal','blockers','because','ventricular-fibrillation','hemodynamic-deterioration','generalize','older','propranolol-label','references','into','permission','treat','guideline','unstable','hemodynamic','instability','attributable','calls','immediate','synchronized','electrical','repeated','beta-blocker','this','chart','anticoagulation','airway','rate-slowing','drugs','can','increase','beta-1','selectivity','eliminate','nonselective','contraindicated','evaluate','any','therapy','new','start','established','stable','perioperatively','appropriate','elective','initiate','optimally','days','surgery','assess','tolerance','titrate','newly','day','when','there','need','prohibit','acute','aha','acc','recommendations','alpha','blockade','beta','use','alone','may','mask','hypoglycemic','prolonged','especially','while','formulation','infusions','mcg','infusion','verify','actual','vial','bag','infer','drug','name','substitute','oral','extended-release','formulations','products'],2,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('beta-blocker-safety','| Check | Pertinent detail |
|---|---|
| **Scope** | Adult monitored IV quick reference, not pediatric, obstetric, thyroid-storm, overdose or outpatient oral-titration protocols. Confirm indication, concentration, local protocol and patient-specific BP/HR targets. |
| **Before dosing** | Check ECG/rhythm, BP, perfusion, volume status and ventricular function. **Do not suppress compensatory tachycardia from hypovolemia.** Monitor ECG and BP during administration; reduce/stop for clinically significant hypotension or bradyarrhythmia. ([Esmolol label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf); [Metoprolol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205)) |
| **Cardiac risks** | **Do not give in cardiogenic shock, decompensated HF or severe bradycardia.** Significant AV block/sinus-node disease requires product-specific assessment; a pacemaker does not remove hypotension or negative-inotropy risk. Metoprolol''s US acute-MI label also contraindicates **HR <45/min, SBP <100 mmHg or PR ≥0.24 sec**; these are label-specific thresholds, not universal treatment targets. ([Metoprolol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205); [Esmolol label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf)) |
| **Pre-excited AF / WPW** | **Avoid beta-blockers and other AV-nodal blockers in pre-excited AF** because of ventricular-fibrillation/hemodynamic-deterioration risk. Do not generalize older propranolol-label references to “WPW” into permission to treat pre-excited AF. ([AF guideline](https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193)) |
| **Unstable AF** | Hemodynamic instability attributable to AF calls for **immediate synchronized electrical cardioversion**, not repeated beta-blocker dosing. This chart is not a cardioversion or anticoagulation protocol. ([AF guideline](https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193)) |
| **Interactions / airway** | Verapamil, diltiazem, digoxin and other rate-slowing drugs can increase bradycardia/block risk. **Beta-1 selectivity does not eliminate bronchospasm risk.** Nonselective labetalol/propranolol are contraindicated in asthma; evaluate airway disease before any beta-blocker. ([Metoprolol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205); [Labetalol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492); [Propranolol label](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f14ea537-dd5c-4c78-9037-9a85e9e610ef)) |
| **Chronic therapy / new start** | **Continue established stable beta-blocker therapy** perioperatively as clinically appropriate. For a new elective indication, initiate **optimally >7 days before surgery** to assess tolerance/titrate. **Do not newly initiate on surgery day when there is no immediate need**; this does not prohibit treatment of an acute indication. ([2024 AHA/ACC guideline recommendations](https://professional.heart.org/-/media/PHD-Files-2/Science-News/2/2024/2024-Guideline-for-Perioperative-Cardiovascular-Management-slide-set.pdf?sc_lang=en)) |
| **Pheochromocytoma / glucose** | For pheochromocytoma, initiate appropriate **alpha blockade before beta blockade**; do not use beta blockade alone. Beta-blockers may mask hypoglycemic tachycardia and increase severe/prolonged hypoglycemia risk, especially while fasting. ([Metoprolol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=17205); [Landiolol label](https://www.rapiblyk.com/fileadmin/user_upload/MediaLibrary_Rapiblyk/Documents/Rapiblyk_Full_Prescribing_Information.pdf)) |
| **Units / formulation** | Esmolol and landiolol infusions: **mcg/kg/min**. Labetalol infusion: **mg/min**. Esmolol **500 mcg/kg = 0.5 mg/kg**. Verify actual vial/bag concentration; do not infer mL from drug name or substitute oral extended-release formulations for IV products. ([Esmolol label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/019386s053lbl.pdf); [Labetalol label](https://labeling.pfizer.com/ShowLabeling.aspx?id=4492); [Landiolol label](https://www.rapiblyk.com/fileadmin/user_upload/MediaLibrary_Rapiblyk/Documents/Rapiblyk_Full_Prescribing_Information.pdf)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

commit;
