-- Authorized adult perioperative hypotension quick charts.
begin;

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('hypotension-bolus','hypotension-dosing','Hypotension Dosing','IV bolus chart',array['hypotension','low blood pressure','low BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','bolus','push','push dose','rescue','phenylephrine','Neo','Neo-Synephrine','ephedrine','Akovaz','Corphedra','norepinephrine','noradrenaline','norepi','Levophed','epinephrine','adrenaline','epi','vasopressin','Vasostrict','low HR','bradycardia','tachyphylaxis','off label','units','mcg','mg','medication','pertinent','details','initially','titrate','repeat','boluses','response','labeled','range','rapid','onset','effect','may','persist','min','raises','vascular','tone','can','cause','reflex','and','decreased','cardiac','output','caution','with','ventricular','dysfunction','inadequate','preload','fda','label','review','sulfate','needed','maximum','total','useful','when','transient','accompanies','low','watch','tachycardia','arrhythmias','switch','strategy','wanes','the','concentrate','requires','dilution','verify','actual','product','off-label','not','infusion','regimen','use','only','under','established','anesthesia','protocol','verified','dilute','syringe','immediate','ecg','reassessment','for','persistent','transition','titrated','excessive','vasoconstriction','arrhythmia','extravasation','stanford','reference','every','push-dose','bridge','monitored','while','definitive','treatment','published','prepared','cardiac-arrest','anaphylaxis','tachyarrhythmia','myocardial','ischemia','unit','specialist','fda-labeled','shock','reserve','selected','vasoplegia','local','reassess','before','further','reduced'],0,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('hypotension-bolus','| Medication | Adult IV dose · pertinent details |
|---|---|
| **Phenylephrine** | **50–100 mcg IV initially**; titrate repeat boluses to response. Labeled bolus range **50–250 mcg**. Rapid onset; effect may persist **up to 20 min**. Raises vascular tone; can cause **reflex bradycardia and decreased cardiac output**. Caution with ventricular dysfunction or inadequate preload. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/216830s000lbl.pdf); [Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Ephedrine sulfate** | **5–10 mg IV**, repeat as needed to BP response; **maximum total 50 mg**. Useful when transient hypotension accompanies a low HR. Watch **tachycardia, arrhythmias and tachyphylaxis**; switch strategy if response wanes. The **50 mg/mL concentrate requires dilution**; verify the actual product. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/208609s012lbl.pdf); [Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Norepinephrine** | **4–8 mcg IV**: **off-label perioperative rescue bolus**, not the labeled infusion regimen. Use only under an established anesthesia protocol with a verified dilute syringe and immediate BP/ECG reassessment. For persistent hypotension, transition to a titrated infusion. Watch excessive vasoconstriction, bradycardia, arrhythmia and extravasation. ([Stanford anesthesia reference](https://cvanes.stanford.edu/perioperative-vasoactives/); [Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Epinephrine** | **5–20 mcg IV every 1–5 min as needed**: **off-label push-dose bridge** for monitored hypotension while definitive treatment/infusion is established. Published dilution **10 mcg/mL**; verify the prepared syringe. **Not a cardiac-arrest or anaphylaxis dosing protocol.** Watch tachyarrhythmia and myocardial ischemia. ([Perioperative review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Vasopressin** | **0.5–1 unit IV**: **off-label specialist perioperative bolus**, not the FDA-labeled shock infusion. Reserve for selected vasoplegia under local anesthesia protocol; reassess before further dosing. Watch ischemia and reduced cardiac output. Dose in **units, not mg or mcg**. ([Stanford anesthesia reference](https://cvanes.stanford.edu/perioperative-vasoactives/); [FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217569Orig1s001lbl.pdf)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('hypotension-infusion','hypotension-dosing','Hypotension Dosing','IV infusion chart',array['hypotension','low blood pressure','low BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','infusion','drip','pressor','vasopressor','titration','maximum','phenylephrine','Neo','Neo-Synephrine','norepinephrine','noradrenaline','norepi','Levophed','epinephrine','adrenaline','epi','vasopressin','Vasostrict','dopamine','Intropin','septic shock','post cardiotomy','vasoplegia','ideal body weight','IBW','lactate','MAOI','pheochromocytoma','units','medication','pertinent','details','labeled','mcg','min','titrated','effect','not','exceed','treat','volume','depletion','acidosis','watch','bradycardia','reduced','cardiac','output','and','ischemia','inspect','site','verify','formulation','ready-to-use','bags','concentrates','are','interchangeable','preparations','fda','label','review','levophed','reference','range','titrate','this','universal','stanford','anesthesia','for','severe','acute','start','typical','maintenance','individualized','response','these','separate','conventions','correct','hypovolemia','monitor','rhythm','wean','rather','than','abruptly','stop','prescribing','information','hemodynamics','ceiling','septic-shock','using','ideal','body','weight','adjust','every','map','goal','shock','regimen','tachyarrhythmias','hyperglycemia','increased','vasostrict','adjunct','septic','post-cardiotomy','increase','limited','data','above','respectively','use','lowest','effective','coronary','mesenteric','limb','index','sodium','changes','permits','increases','according','tolerability','routine','target','hypoxia','contraindicated','substantial','reduction','required','after','recent','maoi','contemporary','role','because','arrhythmias','unpredictable'],1,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('hypotension-infusion','| Medication | Adult IV infusion · titration · pertinent details |
|---|---|
| **Phenylephrine** | Labeled perioperative infusion **0.5–1.4 mcg/kg/min**, titrated to BP effect; **do not exceed 200 mcg/min**. Treat volume depletion/acidosis. Watch bradycardia, reduced cardiac output and ischemia; inspect IV site. Verify formulation: ready-to-use bags and concentrates are **not interchangeable preparations**. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/216830s000lbl.pdf); [Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Norepinephrine (Levophed)** | **Perioperative reference range: 0.02–0.1 mcg/kg/min**, titrate to effect; this is **not a universal maximum**. ([Stanford anesthesia reference](https://cvanes.stanford.edu/perioperative-vasoactives/)) **Label for severe acute hypotension:** start **8–12 mcg/min**; typical maintenance **2–4 mcg/min**, individualized to response. These are separate dosing conventions. Correct hypovolemia; monitor BP/rhythm and IV site; **wean rather than abruptly stop**. ([Prescribing information](https://www.dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=728734e7-1684-4b37-980c-f1dfd408b436&type=display)) |
| **Epinephrine** | **Perioperative reference range: 0.01–0.15 mcg/kg/min**, titrate to hemodynamics; not a universal ceiling. ([Stanford anesthesia reference](https://cvanes.stanford.edu/perioperative-vasoactives/)) **Septic-shock label:** **0.05–2 mcg/kg/min using ideal body weight**; adjust by **0.05–0.2 mcg/kg/min**, e.g. every **10–15 min**, to MAP goal. This is a separate shock regimen. Watch tachyarrhythmias, ischemia, hyperglycemia and increased lactate. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/215425s000lbl.pdf)) |
| **Vasopressin (Vasostrict)** | Perioperative adjunct **0.01–0.04 units/min** for vasoplegia. ([Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) **Label:** septic shock start **0.01 units/min**; post-cardiotomy shock start **0.03 units/min**. Increase **0.005 units/min every 10–15 min**; limited data above **0.07** and **0.1 units/min**, respectively. Use lowest effective dose. Watch coronary/mesenteric/limb ischemia, reduced cardiac index and sodium changes. **Units/min, not units/h.** ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217569Orig1s001lbl.pdf)) |
| **Dopamine** | **Start 2–5 mcg/kg/min**; label permits increases of **5–10 mcg/kg/min** according to response/tolerability; **maximum 50 mcg/kg/min**, not a routine target. Correct hypovolemia, acidosis and hypoxia. **Contraindicated in pheochromocytoma**; substantial dose reduction required after recent MAOI use. ([FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/018826s051lbl.pdf)) Limited contemporary perioperative role because of **arrhythmias and unpredictable response**. ([Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

insert into public.quick_reference_catalog
  (id,reference_id,reference_title,title,keywords,sort_order,is_published)
values ('hypotension-safety','hypotension-dosing','Hypotension Dosing','Selection & safety chart',array['hypotension','low blood pressure','low BP','adult','IV','intravenous','perioperative','periop','postoperative','PACU','dose','dosing','selection','safety','monitoring','concentration','units','extravasation','phentolamine','norepinephrine','Levophed','dopamine','ischemia','peripheral IV','central access','low HR','preload','cardiac output','volume','anesthetic depth','vasoplegia','blood pressure target','check','pertinent','detail','scope','monitored','reference','not','pediatric','obstetric','cardiac-arrest','anaphylaxis','protocols','shock-specific','label','regimens','are','marked','separately','automatic','calculations','treat','the','mechanism','assess','anesthetic','effect','and','ventricular','function','correct','cause','while','supporting','perfusion','higher','does','guarantee','adequate','cardiac','output','substitute','vasoconstriction','for','needed','resuscitation','apsf','review','match','physiology','vasodilation','with','phenylephrine','may','fit','low','ephedrine','transient','myocardial','depression','consider','agent','inotropic','support','rather','than','pure','vasoconstrictor','catecholamine-resistant','vasopressin','adjunct','evaluating','bolus','catecholamine','boluses','mcg','distinguish','min','from','verify','syringe','bag','pump','settings','never','infer','drug','name','fda','stanford','access','frequent','continuous','assessment','ecg','iv-site','surveillance','use','appropriate','large','vein','follow','local','peripheral-pressor','policy','escalating','prolonged','need','central','invasive','titrate','individualized','targets','suspected','injury','needs','immediate','management','labels','specify','infiltration','normal','saline','soon','possible','benefit','described','within','this','antidote','protocol'],2,true)
on conflict (id) do update set reference_id=excluded.reference_id,
  reference_title=excluded.reference_title,title=excluded.title,keywords=excluded.keywords,
  sort_order=excluded.sort_order,is_published=excluded.is_published;
insert into public.quick_reference_sections (id,body,version)
values ('hypotension-safety','| Check | Pertinent detail |
|---|---|
| **Scope** | Adult, monitored perioperative reference. Not pediatric, obstetric, cardiac-arrest or anaphylaxis protocols. Shock-specific label regimens are marked separately. No automatic dose or concentration calculations. |
| **Treat the mechanism** | Assess anesthetic effect, volume/preload, HR and ventricular function; correct the cause while supporting perfusion. A higher BP does **not** guarantee adequate cardiac output. Do not substitute vasoconstriction for needed volume resuscitation. ([APSF](https://www.apsf.org/article/perioperative-hypotension/); [Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Match physiology** | Vasodilation with adequate HR: phenylephrine or norepinephrine may fit. Low HR: ephedrine may fit transient hypotension. Myocardial depression: consider an agent with inotropic support rather than a pure vasoconstrictor. Catecholamine-resistant vasoplegia: vasopressin may be an adjunct. Not a substitute for evaluating the cause. ([Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Dose and concentration** | Ephedrine bolus: **mg**. Catecholamine/phenylephrine boluses: **mcg**. Vasopressin: **units**. Distinguish **mcg/min** from **mcg/kg/min** and **units/min** from **units/h**. Verify syringe/bag label and pump settings; never infer an mL dose from the drug name. ([FDA ephedrine label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/208609s012lbl.pdf); [Stanford reference](https://cvanes.stanford.edu/perioperative-vasoactives/)) |
| **Monitoring / IV access** | Frequent or continuous BP assessment, ECG, perfusion and IV-site surveillance. Use an appropriate large vein and follow local peripheral-pressor policy; escalating/prolonged support may need central access and invasive monitoring. Titrate to individualized BP/perfusion targets. ([Norepinephrine label](https://www.dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=728734e7-1684-4b37-980c-f1dfd408b436&type=display); [Review](https://pmc.ncbi.nlm.nih.gov/articles/PMC13413041/)) |
| **Extravasation** | Suspected injury needs immediate local extravasation management. For **norepinephrine or dopamine**, labels specify adult infiltration of **phentolamine 5–10 mg in 10–15 mL normal saline**, as soon as possible; local benefit described within **12 h**. This is **not a vasopressin antidote protocol**. ([Norepinephrine label](https://www.dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=728734e7-1684-4b37-980c-f1dfd408b436&type=display); [Dopamine label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/018826s051lbl.pdf)) |','2026-09-27')
on conflict (id) do update set body=excluded.body,version=excluded.version,updated_at=now();

commit;
