// EP clinical navigation groups; generated by build-ep.mjs.
const surgicalEpGroups = <String, List<String>>{
  "EP ablation & cardioversion": [
    "atrial-fibrillation-ablation-pulmonary-vein-isolation",
    "atrial-flutter-ablation-cavotricuspid-isthmus",
    "svt-ablation-avnrt-avrt",
    "ventricular-tachycardia-vt-ablation",
    "elective-cardioversion-dccv",
    "tee-guided-cardioversion",
    "electrophysiology-ep-study",
  ],
  "Cardiac devices": [
    "permanent-pacemaker-implantation",
    "icd-aicd-placement",
    "crt-p-crt-d-implantation",
    "pacemaker-icd-generator-change",
    "implantable-loop-recorder-ilr-placement",
  ],
  "Structural heart interventions": [
    "tavr-transcatheter-aortic-valve-replacement",
    "mitraclip-teer-transcatheter-edge-to-edge-repair",
    "transcatheter-tricuspid-interventions",
    "watchman-left-atrial-appendage-occlusion-laao",
    "asd-pfo-closure-percutaneous",
    "adult-vsd-device-closure",
    "transcatheter-pulmonary-valve-replacement",
    "transcatheter-mitral-valve-replacement",
    "aortic-valve-in-valve-tavr",
    "mitral-valve-in-valve-tmvr",
  ],
  "Special & high-risk cath-lab cases": [
    "lead-extraction-transvenous",
    "ice-guided-structural-planning",
    "cardiac-catheterization-diagnostic",
    "pci-with-hemodynamic-support-high-risk-pci",
  ],
};
